# Generated by Django 3.1.6 on 2021-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210320_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
