# Generated by Django 3.1.6 on 2021-03-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idcard',
            field=models.ImageField(upload_to='book/'),
        ),
    ]
