# Generated by Django 3.1.6 on 2021-03-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210314_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idcard',
            field=models.ImageField(upload_to='idcard/'),
        ),
    ]
