# Generated by Django 3.1.6 on 2021-05-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_education_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joindate',
            field=models.DateField(),
        ),
    ]
