# Generated by Django 3.1.6 on 2021-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='month',
            field=models.CharField(choices=[('january', 'Jan'), ('feburary', 'Feb'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'Aug'), ('september', 'Sept'), ('october', 'Oct'), ('november', 'Nov'), ('december', 'Dec')], max_length=10),
        ),
    ]
