# Generated by Django 3.1.6 on 2021-05-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210512_1357'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuprequest',
            name='user',
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
    ]
